apiVersion: ripsaw.cloudbulldozer.io/v1alpha1
kind: Benchmark
metadata:
  name: uperf-benchmark
  namespace: my-ripsaw
spec:
  metadata_collection: false
  clustername: myk8scluster
  #test_user: username_to_attach_to_metadata
  workload:
    # cleanup: true
    name: uperf
    args:
      image: quay.io/tuan_hoang1/uperf_wrapper:latest
      serviceip: false
      hostnetwork: true
      pin: true
      multus:
        enabled: false
      pin_server: "master-1.zocp.ibm.com"
      pin_client: "master-2.zocp.ibm.com"
      samples: 3
      kind: pod
      pair: 1
      test_types:
        - stream
        - rr
      protos:
        - tcp
        - udp
      sizes:
        - 64
        - 1024
        - 16384
      nthrs:
        - 1
      runtime: 60
